import { readdirSync, readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..');
const SVG_DIR = join(ROOT, 'svg');
const ICONS_OUT = join(ROOT, 'src', 'icons', 'index.ts');
const TYPES_OUT = join(ROOT, 'types', 'icon-names.d.ts');
const VSCODE_OUT = join(ROOT, 'types', 'vscode.html-custom-data.json');

type Entry = { name: string; variant: 'fill' | 'line'; key: string; svg: string };

function normalizeSvg(raw: string): string {
  let s = raw.trim();
  s = s.replace(/<\?xml[^>]*\?>\s*/g, '');
  s = s.replace(/<!--[\s\S]*?-->/g, '');
  s = s.replace(/>\s+</g, '><');
  s = s.replace(/<svg\b([^>]*)>/, (_m, attrs: string) => {
    let a = attrs;
    a = a.replace(/\s+(width|height)="[^"]*"/g, '');
    return `<svg${a}>`;
  });
  s = s.replace(/fill="#1A1A1C"/gi, 'fill="currentColor"');
  return s;
}

function parseFilename(file: string): { name: string; variant: 'fill' | 'line' } | null {
  const m = /^(.+)_(fill|line)\.svg$/.exec(file);
  if (!m) return null;
  return { name: m[1]!, variant: m[2] as 'fill' | 'line' };
}

function jsStringLiteral(s: string): string {
  return `'${s.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
}

function main() {
  const files = readdirSync(SVG_DIR).filter((f) => f.endsWith('.svg')).sort();
  const entries: Entry[] = [];
  const namesSet = new Set<string>();

  for (const file of files) {
    const parsed = parseFilename(file);
    if (!parsed) {
      console.warn(`[build-icons] skip (unexpected filename): ${file}`);
      continue;
    }
    const raw = readFileSync(join(SVG_DIR, file), 'utf8');
    const svg = normalizeSvg(raw);
    entries.push({
      name: parsed.name,
      variant: parsed.variant,
      key: `${parsed.name}_${parsed.variant}`,
      svg,
    });
    namesSet.add(parsed.name);
  }

  const names = [...namesSet].sort();
  const fillMissing = names.filter((n) => !entries.some((e) => e.name === n && e.variant === 'fill'));
  const lineMissing = names.filter((n) => !entries.some((e) => e.name === n && e.variant === 'line'));
  if (fillMissing.length || lineMissing.length) {
    console.warn('[build-icons] variants missing:', { fillMissing, lineMissing });
  }

  mkdirSync(dirname(ICONS_OUT), { recursive: true });
  const iconsBody = entries
    .map((e) => `  ${JSON.stringify(e.key)}: ${jsStringLiteral(e.svg)},`)
    .join('\n');
  const iconsTs = `// AUTO-GENERATED by scripts/build-icons.ts. Do not edit.
export const icons: Record<string, string> = {
${iconsBody}
};
`;
  writeFileSync(ICONS_OUT, iconsTs);

  mkdirSync(dirname(TYPES_OUT), { recursive: true });
  const namesUnion = names.map((n) => `  | ${JSON.stringify(n)}`).join('\n');
  const typesTs = `// AUTO-GENERATED by scripts/build-icons.ts. Do not edit.
export type IconName =
${namesUnion};

export type IconVariant = 'fill' | 'line';
`;
  writeFileSync(TYPES_OUT, typesTs);

  const vscode = {
    version: 1.1,
    tags: [
      {
        name: 'dga-icon',
        description:
          'Digital Agency icon Web Component. Switch icons via the `name` attribute.',
        attributes: [
          {
            name: 'name',
            description: 'Icon name.',
            values: names.map((n) => ({ name: n })),
          },
          {
            name: 'variant',
            description: 'Icon style variant.',
            values: [{ name: 'fill' }, { name: 'line' }],
          },
          { name: 'size', description: 'CSS length or unitless pixel value. Default: 24.' },
          { name: 'color', description: 'CSS color. Default: currentColor.' },
        ],
        references: [
          {
            name: 'Digital Agency design system',
            url: 'https://design.digital.go.jp/',
          },
        ],
      },
    ],
  };
  mkdirSync(dirname(VSCODE_OUT), { recursive: true });
  writeFileSync(VSCODE_OUT, JSON.stringify(vscode, null, 2) + '\n');

  console.log(
    `[build-icons] wrote ${entries.length} icons (${names.length} names) \u2192 src/icons/index.ts, types/icon-names.d.ts, types/vscode.html-custom-data.json`,
  );
}

main();
